package com.mz363.FinanceManager.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import java.util.Date;

@DynamoDBTable(tableName = "expense")
public class Expense implements Serializable {

    private String category;
    private Date date;
    private double cost;
    private String description;
    private String tag;
    private String id;

    @DynamoDBRangeKey
    public String getCategory() {
        return category;
    }

    @DynamoDBAttribute
    public Date getDate() {
        return date;
    }

    @DynamoDBAttribute
    public double getCost() {
        return cost;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    @DynamoDBAttribute
    public String getTag() {
        return tag;
    }

    @DynamoDBHashKey(attributeName = "expenseId")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public void setCost(double cost) {
        this.cost = cost;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }

    public void setId(String id) {
        this.id = id;
    }
}
