package com.mz363.FinanceManager.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.io.Serializable;
import java.util.Date;

@DynamoDBTable(tableName = "income")
public class Income implements Serializable {

    private String id;
    private Date date;
    private String type;
    private double earning;
    private String description;
    private String tag;

    @DynamoDBHashKey(attributeName = "incomeId")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public Date getDate() {
        return date;
    }

    @DynamoDBRangeKey
    public String getType() {
        return type;
    }

    @DynamoDBAttribute
    public double getEarning() {
        return earning;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    @DynamoDBAttribute
    public String getTag() {
        return tag;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setEarning(double earning) {
        this.earning = earning;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setTag(String tag) {
        this.tag = tag;
    }
}
